language: node_js
sudo: true
node_js:
  - '8.9.0'

before_install:
  - npm install -g typescript
  - npm install @types/node -g
  - npm install @angular/cli -g
  - npm install typescript -g

install:
  - npm install
